### ISSUE TITLE
File naming bug?

### ISSUE THREAD

**Issue by Vozf** [leon-w/panopto-dl#12]
When I try to dl from live.tum I get filename "Playlist" instead of [subject_name][lecture_name] as it used to be

**Comment by Vozf** [comment]
This lecture somehow recorded audio only. So that might be a particular recording issue(concepts of c++). I'll let you know if other lectures also have that bug

**Comment by Vozf** [comment]
Yeah, the bug persists with other lectures. Seems new layout broke the way title was grabbed from the page

**Comment by Vozf** [comment]
example https://live.rbg.tum.de/w/LC/40347/CAM

**Comment by leon-w** [comment]
So far i don't have a proper way to get the video names for TUM Live. Instead, they get generated based on the DOM of the website. But as the website layout gets updated, this is prone to breaking.

In case something like this happens in the future, it should be relatively easy to fix by adapting this function here that gets injected into the page to return the video name:
https://github.com/leon-w/panopto-dl/blob/6c0d7b4fe6ffbc93f956a4116619f17cfd0e48d8/src/platforms/tum-live.ts#L4-L17

**Comment by Vozf** [comment]
Thank you for continued support
