### ISSUE TITLE
Panopto webcam+slides. Only slides downloaded, no audio

### ISSUE THREAD

**Issue by Vozf** [leon-w/panopto-dl#16]
https://tum.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=91dfc3ca-91d5-4123-94c8-b16a00babe2c&instance=moodle
Probably would be nice to at least have the audio with the slides if blending videos isn't feasible

**Comment by Vozf** [comment]
Also it seems like I get 2 dl links in the extension, but they are both slides recordings

**Comment by leon-w** [comment]
As i dont have access to the example video you provided, i fear that i cant really debug the issue.
If you need help adressing the problem yourself, let me know.

**Comment by Vozf** [comment]
:(
Possibly you can get access by enrolling in the course [advanced microeconomics](https://campus.tum.de/tumonline/ee/ui/ca2/app/desktop/#/slc.tm.cp/student/courses/950733540?$scrollTo=toc_overview)
Thanks anyway

**Comment by leon-w** [comment]
As i finished my studies, that's unfortunately no longer an option for me, sorry!

**Comment by Vozf** [comment]
I can probably try to address the issue. So as I've said there are 2 videos. I've also uploaded the html code of the page(Won't open in chrome as you don't have videos access, but it can help you undestand the page layout)
As far as I understood webcam video has the mic sound and slides are just slides. 
Now extension finds 2 videos, but they are both only downloading slides
![image](https://github.com/leon-w/panopto-dl/assets/22998537/26958ff2-4345-436d-9712-389028b6af2f)

Ideally I'd want to get a single video where in corner I would see the webcam.
What direction should I look into?
![image](https://github.com/leon-w/panopto-dl/assets/22998537/13a2876f-4879-46f6-ab03-57379c7cca7c)
[Uploading Exercise 1 (Part 1) - May 8, 2024.html.txt…]()

**Comment by Vozf** [comment]
Nevermind. This extension actually handles double videos. 
https://github.com/Panopto-Video-DL/Panopto-Video-DL
Thanks anyway
