### ISSUE TITLE
When pasting multidownload prompt(download all) only the first line of the prompt gets pasted in the windows cmd

### ISSUE THREAD

**Issue by Vozf** [leon-w/panopto-dl#6]
After download all I get this command in the clipboard
```
ffmpeg.exe -i "kk" -c copy -bsf:a aac_adtstoasc "file:file1.mp4" && \
ffmpeg.exe -i "kkkk" -c copy -bsf:a aac_adtstoasc "file:file2.mp4"
```
When I try to paste it in cmd only the first line is pasted and the executed(line break is considered "Enter" press)
```
ffmpeg.exe -i "kk" -c copy -bsf:a aac_adtstoasc "file:file1.mp4" && \
```
To fix it I have to manually remove line breaks and `\` symbols. creating a single line command instead should fix the issue

**Comment by leon-w** [comment]
Thank you for reporting this issue. I only tested the generated command for `bash` / `zsh`. I wanted to make the command a bit more readable but if that causes issues with `cmd`, it makes sense to make the suggested change.
